### ISSUE TITLE
dotnet pack doesn't generate pdb

### ISSUE THREAD

**Issue by Lanayx** [fable-compiler/Fable.Package.SDK#7]
As soon as there is no pdb genereated, I can't upload .snupkg file on nuget, it errors with  "The package does not contain any symbol (.pdb) files.". Is it an expected behaviour?

![image](https://github.com/user-attachments/assets/50f8c88b-e148-48d4-b182-314ba864d560)

I used

```
<FablePackageType>binding</FablePackageType>
<PackageTags>fable-javascript</PackageTags>
<IncludeSymbols>true</IncludeSymbols>
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

**Comment by MangelMaxime** [comment]
I am not sure, I never saw complains coming from NuGet CLI when generating packages.

I think you need to remove:

```xml
<IncludeSymbols>true</IncludeSymbols>
<SymbolPackageFormat>snupkg</SymbolPackageFormat>
```

This MSBuild project set `<DebugType>embedded</DebugType>`, which if I understand correctly means that the symbol file is included in the package directly.

**Comment by Lanayx** [comment]
@MangelMaxime you are right, `<DebugType>embedded</DebugType>` is the reason .pdb file is not generated. But this makes package heavier, that's why I moved to .snupkg model for my packages where .pdb is not included in the package itself and only used by IDE. I guess for Fable it doesn't matter since those dlls are only used for devlopment and are not included into the published artifacts, so I'm ok to close the ticket. Thanks for finding time to respond!

**Comment by MangelMaxime** [comment]
Perhaps, it possible to set the `DebugType` in your project to disable that. Depending on which order MSBuild load the information.

Or if having package a bit heavier is too much of a problem, it is also possible to add a flag to tell `Fable.Package.SDK` to not include the `DebugType` rule.

**Comment by Lanayx** [comment]
I don't see this as a big issue, so we can keep it as is for now
